#!/usr/bin/env bash
#
# Run Companion and cuebooth-server on this host, reachable from a laptop over
# Tailscale, so the system can be driven by a real client without the production
# PC.
#
#   scripts/devstack.sh up        # start both, print where to point a client
#   scripts/devstack.sh status    # what is running, and whether the surface registered
#   scripts/devstack.sh logs [companion|server]
#   scripts/devstack.sh restart   # rebuild and restart the server only
#   scripts/devstack.sh down      # stop both; Companion's config survives
#
# Knobs:
#   DEVSTACK_COMPANION_VERSION   Companion image tag (default: the production-PC version)
#   DEVSTACK_BIND                extra address to publish on (default: this host's Tailscale IPv4)
#   DEVSTACK_HOST                name printed in connect instructions (default: Tailscale DNS name)
#   DEVSTACK_DIR                 state directory (default: <repo>/.devstack)
#   CONTAINER_ENGINE             podman or docker (default: whichever is installed)
#
# This is a manual fixture, not CI. The live protocol tests are
# scripts/companion-live-test.sh, which pins versions and runs headless.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${DEVSTACK_DIR:-$REPO_ROOT/.devstack}"
COMPANION_DIR="$STATE_DIR/companion"
CONFIG_FILE="$STATE_DIR/cuebooth.toml"
SERVER_LOG="$STATE_DIR/server.log"
SERVER_PID="$STATE_DIR/server.pid"
SERVER_BIN="$STATE_DIR/cuebooth-server"

VERSION="${DEVSTACK_COMPANION_VERSION:-v3.4.1}"
IMAGE="ghcr.io/bitfocus/companion/companion:${VERSION}"
CONTAINER="cuebooth-devstack"

ADMIN_PORT=8000
SAT_PORT=16622
SERVER_PORT=7878

die() { echo "error: $*" >&2; exit 1; }

engine() {
  if [[ -n "${CONTAINER_ENGINE:-}" ]]; then echo "$CONTAINER_ENGINE"; return; fi
  for candidate in podman docker; do
    if command -v "$candidate" >/dev/null 2>&1; then echo "$candidate"; return; fi
  done
  die "no container engine found (need podman or docker)"
}

# bind_addr is the address to publish on besides loopback. Companion's admin UI
# has no authentication, so this deliberately does not publish on 0.0.0.0.
bind_addr() {
  if [[ -n "${DEVSTACK_BIND:-}" ]]; then echo "$DEVSTACK_BIND"; return; fi
  local ip
  ip="$(tailscale ip -4 2>/dev/null | head -1 || true)"
  [[ -n "$ip" ]] || die "no Tailscale IPv4 found; set DEVSTACK_BIND to the address to publish on"
  echo "$ip"
}

# host_name is what a client should be pointed at.
host_name() {
  if [[ -n "${DEVSTACK_HOST:-}" ]]; then echo "$DEVSTACK_HOST"; return; fi
  local dns
  dns="$(tailscale status --json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || true)"
  if [[ -n "$dns" ]]; then echo "$dns"; else bind_addr; fi
}

write_config() {
  local bind="$1"
  if [[ -f "$CONFIG_FILE" && "${DEVSTACK_REGENERATE:-0}" != "1" ]]; then
    echo "==> keeping existing $CONFIG_FILE (DEVSTACK_REGENERATE=1 to replace)"
    return
  fi
  cat > "$CONFIG_FILE" <<EOF
# Generated by scripts/devstack.sh. Edit freely — it is only rewritten when
# DEVSTACK_REGENERATE=1.

[server]
listen = "${bind}:${SERVER_PORT}"

[companion]
base_url = "http://127.0.0.1:${ADMIN_PORT}"

[companion.satellite]
addr = "127.0.0.1:${SAT_PORT}"
device_id = "cuebooth"
rows = 4
cols = 8
bitmap_size = 72

# Preset names the client and slide rules use, pointed at page 1 of whatever
# you set up in Companion. Adjust the coordinates to match your buttons;
# "page/row/column", page 1-based, row and column 0-based.
[presets.scene.camera-only]
companion_button = "1/0/0"

[presets.scene.camera-with-slides]
companion_button = "1/0/1"

[presets.streaming.start]
companion_button = "1/1/0"

[presets.streaming.stop]
companion_button = "1/1/1"

[presets.recording.start]
companion_button = "1/2/0"

[presets.recording.stop]
companion_button = "1/2/1"
EOF
  echo "==> wrote $CONFIG_FILE"
}

companion_running() {
  [[ -n "$("$(engine)" ps --filter "name=^${CONTAINER}$" --format '{{.Names}}' 2>/dev/null)" ]]
}

server_running() {
  [[ -f "$SERVER_PID" ]] && kill -0 "$(cat "$SERVER_PID")" 2>/dev/null
}

start_companion() {
  local bind="$1" eng
  eng="$(engine)"
  if companion_running; then
    echo "==> companion already running"
    return
  fi
  # Removed rather than restarted: a container left from an older image tag
  # would otherwise silently keep serving.
  "$eng" rm -f "$CONTAINER" >/dev/null 2>&1 || true
  mkdir -p "$COMPANION_DIR"
  echo "==> pulling $IMAGE"
  "$eng" pull "$IMAGE" >/dev/null

  # The image runs as uid 1000. Under rootless podman that maps to a subuid, so
  # a directory owned by the invoking user is not writable inside the container;
  # keep-id maps them onto each other, which also leaves the config readable on
  # the host. Docker has no equivalent, so it gets a managed volume instead —
  # persistent either way, just less convenient to inspect.
  local storage=()
  if [[ "$(basename "$eng")" == "podman" ]]; then
    storage=(--userns "keep-id:uid=1000,gid=1000" -v "$COMPANION_DIR:/companion:Z")
  else
    storage=(-v "cuebooth-devstack-config:/companion")
  fi

  echo "==> starting companion"
  "$eng" run -d --name "$CONTAINER" \
    "${storage[@]}" \
    -p "127.0.0.1:${ADMIN_PORT}:8000" \
    -p "${bind}:${ADMIN_PORT}:8000" \
    -p "127.0.0.1:${SAT_PORT}:16622" \
    -p "${bind}:${SAT_PORT}:16622" \
    "$IMAGE" >/dev/null

  echo -n "==> waiting for companion's satellite port"
  for _ in $(seq 1 60); do
    if (exec 3<>"/dev/tcp/127.0.0.1/${SAT_PORT}") 2>/dev/null; then
      exec 3>&- 2>/dev/null || true
      echo " ok"
      return
    fi
    echo -n "."
    sleep 1
  done
  echo
  die "companion did not open ${SAT_PORT} — check: $(engine) logs $CONTAINER"
}

start_server() {
  if server_running; then
    echo "==> server already running (pid $(cat "$SERVER_PID"))"
    return
  fi
  echo "==> building server"
  (cd "$REPO_ROOT/server" && go build -o "$SERVER_BIN" ./cmd/cuebooth-server)

  echo "==> starting server"
  # setsid so the stack outlives the shell that started it.
  setsid "$SERVER_BIN" -config "$CONFIG_FILE" >>"$SERVER_LOG" 2>&1 &
  echo $! > "$SERVER_PID"
  sleep 1
  server_running || die "server exited immediately — see $SERVER_LOG"
}

# surface_registered reports whether Companion currently has the CueBooth
# surface, which is the difference between "both processes are up" and "they
# found each other". The server logs one line when a satellite session registers
# and another when it ends, so the later of the two is the current state — a log
# that merely contains a registration may be describing a session since dropped.
surface_registered() {
  local last
  # The log spans every run the stack has had, so lines before the newest
  # "starting" describe a server that is no longer here.
  last="$(awk '
    /cuebooth-server starting/            { latest = "" }
    /companion satellite registered/      { latest = "up" }
    /companion satellite session ended/   { latest = "down" }
    END                                   { print latest }
  ' "$SERVER_LOG" 2>/dev/null)"
  [[ "$last" == "up" ]]
}

# wait_for_surface gives the first connection a moment to land, so `up` reports
# what will be true a second later rather than what is true immediately.
wait_for_surface() {
  for _ in $(seq 1 20); do
    surface_registered && return 0
    sleep 1
  done
  return 1
}

cmd_up() {
  mkdir -p "$STATE_DIR"
  local bind host
  bind="$(bind_addr)"
  host="$(host_name)"
  write_config "$bind"
  start_companion "$bind"
  start_server
  wait_for_surface || true
  echo
  cmd_status
  cat <<EOF

Next, once only:
  1. Open Companion at  http://${host}:${ADMIN_PORT}
  2. Build a page of buttons (Buttons tab). The "internal" connection has
     useful ones — page up/down, a variable display — with no hardware.
  3. Surfaces tab: assign a page to the "cuebooth" surface.

Then, from your laptop:
  cd client && flutter run -d macos      # or windows, chrome, or a device
  ...and connect to  ${host}:${SERVER_PORT}
EOF
}

cmd_down() {
  local eng
  eng="$(engine)"
  if server_running; then
    echo "==> stopping server (pid $(cat "$SERVER_PID"))"
    kill "$(cat "$SERVER_PID")" 2>/dev/null || true
  fi
  rm -f "$SERVER_PID"
  echo "==> removing companion (config kept in $COMPANION_DIR)"
  "$eng" rm -f "$CONTAINER" >/dev/null 2>&1 || true
}

cmd_restart() {
  if server_running; then
    kill "$(cat "$SERVER_PID")" 2>/dev/null || true
    rm -f "$SERVER_PID"
    sleep 1
  fi
  start_server
  wait_for_surface || true
  cmd_status
}

cmd_status() {
  local host
  host="$(host_name)"
  if companion_running; then
    echo "companion   up     http://${host}:${ADMIN_PORT}   (satellite ${SAT_PORT})"
  else
    echo "companion   down"
  fi
  if server_running; then
    echo "server      up     ws://${host}:${SERVER_PORT}/ws   (pid $(cat "$SERVER_PID"))"
  else
    echo "server      down"
  fi
  if companion_running && server_running; then
    if surface_registered; then
      echo "surface     registered with Companion — assign it a page in Surfaces"
    else
      echo "surface     NOT registered — check $SERVER_LOG and Companion's Satellite API setting"
    fi
  fi
}

cmd_logs() {
  case "${1:-server}" in
    companion) "$(engine)" logs -f "$CONTAINER" ;;
    server)    tail -f "$SERVER_LOG" ;;
    *)         die "logs takes 'companion' or 'server'" ;;
  esac
}

case "${1:-}" in
  up)      cmd_up ;;
  down)    cmd_down ;;
  restart) cmd_restart ;;
  status)  cmd_status ;;
  logs)    shift; cmd_logs "$@" ;;
  *)       sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
